defaults:
  - dataset
  - _self_

meta:
  save_model: true
  use_gcs: false
  bucket_name: mlops-proj
  require_cuda: true
train:
  seed: 42
  epochs: 1
  batch_size: 256
  warmup_ratio: 0.1
  loss: MultipleNegativesRankingLoss # default, good for positive only pairs
  model: all-MiniLM-L6-v2
wandb:
  enabled: false
