meta:
  save_model: true
  use_gcs: false
  bucket_name: mlops-proj
train:
  seed: 42
  epochs: 1
  batch_size: 256
  warmup_ratio: 0.1
  loss: MultipleNegativesRankingLoss # default, good for positive only pairs
wandb:
  enabled: true
