name: CI Pipeline

on:
  push:
    branches: [master, build]
  pull_request:
    branches: [master, build]

jobs:
  format:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --dev

      - name: ruff linter
        run: uv run ruff check .

      - name: ruff formatter
        run: uv run ruff format . --check

      - name: mypy type checking
        run: uv run mypy . --ignore-missing-imports

  test:
    name: Unit Tests
    needs: format # This ensures test runs AFTER format
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --locked --dev

      - name: Run tests & coverage
        run: |
          uv run coverage run -m pytest tests/
          uv run coverage report -m

  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test # only build if tests pass
    if: ${{ github.ref == 'refs/heads/build' && github.event_name == 'push' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Auth with GCP
      uses: google-github-actions/auth@v3
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY}}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v3

    - name: Submit build
      run: gcloud builds submit . --config cloudbuild.yaml --service-account=projects/mlopsproject-484419/serviceAccounts/githubserviceaccount@mlopsproject-484419.iam.gserviceaccount.com
